== Teaching

- DSSP *Data Science Starter Program, 2019*. École Polytechnique Executive Education.

- BNP Cardiff *Data Science Starter Program, 2019*. École Polytechnique Executive Education.

- CSE204 *Machine Learning, 2019*. _Bachelor 2_, École Polytechnique.

- [DK904] *Data Stream Mining 2018/2019*. _M2_ Data and Knowledge Program. Université Paris Saclay. 

- MAP631 *Deep Learning, 2018*. _M2_. École Polytechnique.

- INF554 *Machine Learning I, 2018--2019*. _M1_. École Polytechnique.

- INF581 *Advanced Topics in Artificial Intelligence, 2018*. _M1_. École Polytechnique.

- DSSP *Data Science Starter Program, 2018*. École Polytechnique Executive Education.

- BNP Cardiff *Data Science Starter Program, 2018*. École Polytechnique Executive Education.

- [DK904] *IoT Stream Data Mining 2017/2018*. _M2_ Data and Knowledge Program. Université Paris Saclay

- INF554 *Machine Learning I, 2017--2018*. _M1_. École Polytechnique.

- MAP670 *Methods for Big Data Analytics 2016--2017* _M2_ Datascience Program. École Polytechnique, Université Paris Saclay.

- INF554 *Introduction to Machine Learning, 2016--2017*. _M1_. École Polytechnique.

//(2.5 ECTS, shared with Albert Bifet)
- [DK904] *IoT Stream Data Mining 2016/2017*. _M2_ Data and Knowledge Program. Université Paris Saclay

//(5 ECTS, shared with Jaakko Hollmén) 
- Special Course in Computer and Information Science III P Spring 2015 *Dynamical models for prediction and decision making*. Aalto University.

- *Tratamiento de Datos 2013/2014* (Labs - Procesos Gaussianos). _Máster Universitario en Ingeniería de Telecomunicación_, Universidad Carlos III de Madrid.
    [link:codigo_matlab_1.zip[Código Matlab Part 1], link:codigo_matlab_2.zip[Part 2]]. 

- *Systems and Signals 2013/2014* (Part 1/2) _Grado en Ing. Biomédica_, Universidad Carlos III de Madrid.  
 [link:./talks/Notes_Signals-and-Systems.pdf[Course Notes]]. 

